name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'   # v1.0.0 のようなタグを push したら実行

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller --clean main.spec

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.exe
          body: |
            ## リリースノート
            
            ### Windows版
            [Windows EXEファイル](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/main.exe)
            
            Windows用の実行ファイルをダウンロードしてご利用ください。
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
